#!/bin/zsh

source ~/.zshrc

vars=(EMACS_HOME EMACS EMACSCLIENT EDITOR VISUAL PATH)
for var in $vars; do
  eval "val=\"\$${var}\""
  if [[ -n "$val" ]]; then
    launchctl setenv "$var" "$val"
  fi
done

sleep 1

# Make sure new environment is applied to Finder and Dock, so that applications
# launched from GUI actually use the variables just set.
killall Finder
killall Dock
